name: Deploy to Server

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build React App
        run: npm install && npm run build
        
      - name: Deploy React App
        run: |
          sudo cp -r /var/www/html/my-react-app/build/*  /var/www/html/React-Whitepage-error
